### ISSUE TITLE
can not split 👩‍🦱  correctly

### ISSUE THREAD

**Issue by woshizja** [yumetodo/grapheme-breaker-u10-0#6]
GraphemeBreaker.break('👩‍🦱'); // => ["👩‍", "🦱"]

**Comment by yumetodo** [comment]
`U+1F469 U+200D U+1F9B1` is added at Unicode 11. Try below library which is a fork of this, suppoted Unicode 13.0.0.
https://github.com/taisukef/grapheme-breaker-mjs

This library is now mark as deprecated. And this repo will be archived in a few days.

**Comment by yumetodo** [comment]
closed and archived.
